server:
  port: 8080
spring:
  rabbitmq:
    host: "localhost:5888"
    port: "5672"
    username: "guest"
    password: "guest"
    virtual-host: "/"
  application:
    name: "dojoCA"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb+srv://adminuser:retoSofka123@cluster0.i58xo.mongodb.net/test?retryWrites=true&w=majority"
